"""initial

Revision ID: 6dab3880da05
Revises: 
Create Date: 2026-04-16 11:39:59.557695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dab3880da05'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AppSetting',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('Client',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('lastName', sa.String(), nullable=False),
    sa.Column('firstName', sa.String(), nullable=False),
    sa.Column('middleName', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('phoneNormalized', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('documentsUrl', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.Column('deletedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('Client_phoneNormalized_idx', 'Client', ['phoneNormalized'], unique=False)
    op.create_table('InsuranceCompany',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.Column('deletedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('passwordHash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('theme', sa.String(), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.Column('deletedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('AuditEvent',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('userId', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entityType', sa.String(), nullable=False),
    sa.Column('entityId', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('AuditEvent_createdAt_idx', 'AuditEvent', ['createdAt'], unique=False)
    op.create_index('AuditEvent_userId_idx', 'AuditEvent', ['userId'], unique=False)
    op.create_table('ClientPhone',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('clientId', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('phoneNormalized', sa.String(), nullable=False),
    sa.Column('sortOrder', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clientId'], ['Client.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ClientPhone_clientId_idx', 'ClientPhone', ['clientId'], unique=False)
    op.create_index('ClientPhone_phoneNormalized_idx', 'ClientPhone', ['phoneNormalized'], unique=False)
    op.create_table('HomeNotification',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('userId', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('dedupeKey', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('readAt', sa.DateTime(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userId', 'dedupeKey', name='HomeNotification_userId_dedupeKey_key')
    )
    op.create_index('HomeNotification_userId_readAt_idx', 'HomeNotification', ['userId', 'readAt'], unique=False)
    op.create_table('InsuranceProduct',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('companyId', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('defaultPremiumPct', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.Column('deletedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['companyId'], ['InsuranceCompany.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('InsuranceProduct_companyId_idx', 'InsuranceProduct', ['companyId'], unique=False)
    op.create_table('Policy',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('clientId', sa.String(), nullable=False),
    sa.Column('companyId', sa.String(), nullable=False),
    sa.Column('productId', sa.String(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('insuranceSumS', sa.String(), nullable=True),
    sa.Column('premiumPercent', sa.String(), nullable=True),
    sa.Column('premiumRubles', sa.String(), nullable=False),
    sa.Column('agentIncomeD', sa.String(), nullable=False),
    sa.Column('startDate', sa.DateTime(), nullable=False),
    sa.Column('endDate', sa.DateTime(), nullable=False),
    sa.Column('termDays', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.Column('deletedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clientId'], ['Client.id'], ),
    sa.ForeignKeyConstraint(['companyId'], ['InsuranceCompany.id'], ),
    sa.ForeignKeyConstraint(['productId'], ['InsuranceProduct.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('companyId', 'number', name='Policy_companyId_number_key')
    )
    op.create_index('Policy_clientId_idx', 'Policy', ['clientId'], unique=False)
    op.create_index('Policy_endDate_idx', 'Policy', ['endDate'], unique=False)
    op.create_table('RenewalTask',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('taskNumber', sa.Integer(), nullable=False),
    sa.Column('policyId', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('statusChangedAt', sa.DateTime(), nullable=False),
    sa.Column('snoozedUntil', sa.DateTime(), nullable=True),
    sa.Column('declineReason', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['policyId'], ['Policy.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('taskNumber')
    )
    op.create_index('RenewalTask_policyId_status_idx', 'RenewalTask', ['policyId', 'status'], unique=False)
    op.create_index('RenewalTask_snoozedUntil_idx', 'RenewalTask', ['snoozedUntil'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('RenewalTask_snoozedUntil_idx', table_name='RenewalTask')
    op.drop_index('RenewalTask_policyId_status_idx', table_name='RenewalTask')
    op.drop_table('RenewalTask')
    op.drop_index('Policy_endDate_idx', table_name='Policy')
    op.drop_index('Policy_clientId_idx', table_name='Policy')
    op.drop_table('Policy')
    op.drop_index('InsuranceProduct_companyId_idx', table_name='InsuranceProduct')
    op.drop_table('InsuranceProduct')
    op.drop_index('HomeNotification_userId_readAt_idx', table_name='HomeNotification')
    op.drop_table('HomeNotification')
    op.drop_index('ClientPhone_phoneNormalized_idx', table_name='ClientPhone')
    op.drop_index('ClientPhone_clientId_idx', table_name='ClientPhone')
    op.drop_table('ClientPhone')
    op.drop_index('AuditEvent_userId_idx', table_name='AuditEvent')
    op.drop_index('AuditEvent_createdAt_idx', table_name='AuditEvent')
    op.drop_table('AuditEvent')
    op.drop_table('User')
    op.drop_table('InsuranceCompany')
    op.drop_index('Client_phoneNormalized_idx', table_name='Client')
    op.drop_table('Client')
    op.drop_table('AppSetting')
    # ### end Alembic commands ###
